const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const icon=(name)=>`<svg><use href="#i-${name}"/></svg>`;
const cityInfo={
  'Europe/Istanbul':['İstanbul','Türkiye'],'Europe/London':['Londra','Birleşik Krallık'],'America/New_York':['New York','ABD'],'America/Los_Angeles':['Los Angeles','ABD'],'Europe/Paris':['Paris','Fransa'],'Europe/Berlin':['Berlin','Almanya'],'Europe/Moscow':['Moskova','Rusya'],'Asia/Dubai':['Dubai','BAE'],'Asia/Tokyo':['Tokyo','Japonya'],'Asia/Seoul':['Seul','Güney Kore'],'Asia/Shanghai':['Şanghay','Çin'],'Asia/Singapore':['Singapur','Singapur'],'Asia/Kolkata':['Yeni Delhi','Hindistan'],'Australia/Sydney':['Sidney','Avustralya'],'America/Toronto':['Toronto','Kanada'],'America/Sao_Paulo':['São Paulo','Brezilya']
};
let state,view='world',ringing=null,audioCtx,toneTimer;
const fmtTime=(zone,seconds=false)=>new Intl.DateTimeFormat('tr-TR',{timeZone:zone,hour:'2-digit',minute:'2-digit',second:seconds?'2-digit':undefined,hour12:false}).format(new Date());
const fmtDate=()=>new Intl.DateTimeFormat('tr-TR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
const pad=n=>String(Math.floor(n)).padStart(2,'0');
function duration(ms,centis=false){ms=Math.max(0,ms);const h=Math.floor(ms/3600000),m=Math.floor(ms/60000)%60,s=Math.floor(ms/1000)%60;if(centis)return `${pad(h)}:${pad(m)}.${pad((ms%1000)/10)}`;return h?`${pad(h)}:${pad(m)}:${pad(s)}`:`${pad(m)}:${pad(s)}`;}
function remaining(item){return item.running?Math.max(0,item.deadline-Date.now()):item.remaining;}
function offset(zone){const here=new Date().getTimezoneOffset();const parts=new Intl.DateTimeFormat('en',{timeZone:zone,timeZoneName:'longOffset'}).formatToParts(new Date());const raw=(parts.find(p=>p.type==='timeZoneName')||{}).value||'GMT';const match=raw.match(/GMT([+-])(\d{2}):?(\d{2})?/);const there=match?(match[1]==='+'?1:-1)*(+match[2]*60 + +(match[3]||0)):0;const diff=there+here;if(!diff)return 'Aynı saat';return `${diff>0?'+':'−'}${Math.floor(Math.abs(diff)/60)}${Math.abs(diff)%60?':'+pad(Math.abs(diff)%60):''} saat`;}
async function act(type,data={}){const result=await window.saat.action(type,data);if(!result.ok)toast(result.error);else state=result.state;return result.ok;}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2600);}
function render(){if(!state)return;$('#localTime').textContent=fmtTime('Europe/Istanbul',true);$('#localDate').textContent=fmtDate();renderCities();renderAlarms();renderStopwatch();renderTimers();renderPomodoro();renderAlert();$('#hudToggle span').textContent=state.hud?'HUD’u gizle':'HUD’u göster';}
function renderCities(){$('#cityList').innerHTML=state.cities.filter(z=>z!=='Europe/Istanbul').map(zone=>{const info=cityInfo[zone]||[zone.split('/').pop().replaceAll('_',' '),zone.split('/')[0]];return `<article class="city-card"><div class="city-top"><span>${info[1]}</span><button class="icon-btn" data-remove-city="${zone}" aria-label="${info[0]} şehrini kaldır">${icon('trash')}</button></div><strong>${fmtTime(zone)}</strong><p>${info[0]} · ${offset(zone)}</p></article>`}).join('')||'<div class="empty">Henüz başka bir şehir eklenmedi.</div>';}
function renderAlarms(){const days=['Paz','Pzt','Sal','Çar','Per','Cum','Cmt'];$('#alarmList').innerHTML=state.alarms.map(a=>`<article class="list-item"><strong class="big">${a.time}</strong><div><p>${esc(a.label)}</p><small>${a.days.length?a.days.map(d=>days[d]).join(', '):'Bir kez'}${a.snoozeAt?' · Ertelendi':''}</small></div><button class="toggle ${a.enabled?'on':''}" data-toggle-alarm="${a.id}" aria-label="Alarmı aç veya kapat"></button><button class="icon-btn" data-delete-alarm="${a.id}" aria-label="Alarmı sil">${icon('trash')}</button></article>`).join('')||'<div class="empty">Alarm yok. Sabahını planlamak için bir alarm ekle.</div>';}
function renderStopwatch(){const elapsed=state.stopwatch.elapsed;$('#swValue').textContent=duration(elapsed,true);$('#swToggle').innerHTML=icon(state.stopwatch.running?'pause':'play');$('#lapList').innerHTML=state.stopwatch.laps.map((lap,i)=>`<div class="lap"><span>Tur ${state.stopwatch.laps.length-i}</span><strong>${duration(lap,true)}</strong></div>`).join('');}
function renderTimers(){$('#timerList').innerHTML=state.timers.map(t=>{const left=remaining(t),pct=Math.max(0,Math.min(100,left/t.duration*100));return `<article class="timer-card"><div class="top"><p>${esc(t.label)}</p><button class="icon-btn" data-delete-timer="${t.id}" aria-label="Zamanlayıcıyı sil">${icon('trash')}</button></div><strong>${duration(left)}</strong><div class="progress"><i style="width:${pct}%"></i></div><div class="timer-actions"><button data-toggle-timer="${t.id}">${t.running?'Duraklat':'Devam et'}</button></div></article>`}).join('')||'<div class="empty">Çalışan zamanlayıcı yok.</div>';}
function renderPomodoro(){const p=state.pomodoro,left=p.running?Math.max(0,p.deadline-Date.now()):p.remaining;$('#pomoValue').textContent=duration(left);$('#pomoPhase').textContent=p.phase==='focus'?'ODAKLANMA':p.phase==='short'?'KISA MOLA':'UZUN MOLA';$('#pomoSession').textContent=`${p.session}. seans`;$('#pomoToggle').innerHTML=icon(p.running?'pause':'play');$('#pomoDots').innerHTML=[0,1,2,3].map(i=>`<i class="${i<p.completed%4?'done':''}"></i>`).join('');}
function renderAlert(){const a=state.alerts?.[0];if(a&&!ringing){ringing=a.id;$('#ringTitle').textContent=a.title;$('#ringTime').textContent=new Date(a.at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});$('#snooze').hidden=a.kind!=='alarm';$('#alarmOverlay').hidden=false;startTone();}else if(!a&&ringing){ringing=null;$('#alarmOverlay').hidden=true;stopTone();}}
function startTone(){try{audioCtx=new AudioContext();const ring=()=>{const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.frequency.setValueAtTime(740,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(960,audioCtx.currentTime+.18);gain.gain.setValueAtTime(.001,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.15,audioCtx.currentTime+.03);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.45);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.48)};ring();toneTimer=setInterval(ring,900);}catch{}}
function stopTone(){clearInterval(toneTimer);audioCtx?.close();audioCtx=null;}
function esc(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML;}
function switchView(name){view=name;$$('.view').forEach(el=>el.classList.toggle('active',el.id===name));$$('#nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===name));}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view)});
$$('[data-window]').forEach(b=>b.addEventListener('click',()=>window.saat.window(b.dataset.window)));
$('#hudToggle').addEventListener('click',()=>window.saat.window('hud'));
$('#openCity').addEventListener('click',()=>$('#cityDialog').showModal());
$('#citySelect').innerHTML=Object.entries(cityInfo).filter(([z])=>z!=='Europe/Istanbul').map(([z,v])=>`<option value="${z}">${v[0]} · ${v[1]}</option>`).join('');
$('#addCity').addEventListener('click',async e=>{e.preventDefault();if(await act('city-add',{zone:$('#citySelect').value}))$('#cityDialog').close();});
$('#cityList').addEventListener('click',e=>{const b=e.target.closest('[data-remove-city]');if(b)act('city-remove',{zone:b.dataset.removeCity})});
$('#dayPills').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b)b.classList.toggle('selected')});
$('#alarmForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);act('alarm-add',{time:f.get('time'),label:f.get('label'),days:$$('#dayPills .selected').map(b=>+b.dataset.day)});});
$('#alarmList').addEventListener('click',e=>{let b=e.target.closest('[data-toggle-alarm]');if(b)act('alarm-toggle',{id:b.dataset.toggleAlarm});b=e.target.closest('[data-delete-alarm]');if(b)act('alarm-delete',{id:b.dataset.deleteAlarm});});
$('#swToggle').addEventListener('click',()=>act('sw-toggle'));$('#swReset').addEventListener('click',()=>act('sw-reset'));$('#swLap').addEventListener('click',()=>act('sw-lap'));
$('#timerForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),seconds=+f.get('hours')*3600 + +f.get('minutes')*60 + +f.get('seconds');act('timer-add',{label:f.get('label'),seconds});});
$('#timerList').addEventListener('click',e=>{let b=e.target.closest('[data-toggle-timer]');if(b)act('timer-toggle',{id:b.dataset.toggleTimer});b=e.target.closest('[data-delete-timer]');if(b)act('timer-delete',{id:b.dataset.deleteTimer});});
$('#pomoToggle').addEventListener('click',()=>act('pomo-toggle'));$('#pomoReset').addEventListener('click',()=>act('pomo-reset'));$('#pomoSettings').addEventListener('click',()=>{const p=state.pomodoro;$('#workMins').value=p.work;$('#shortMins').value=p.short;$('#longMins').value=p.long;$('#pomoDialog').showModal()});
$('#savePomo').addEventListener('click',async e=>{e.preventDefault();if(await act('pomo-settings',{work:+$('#workMins').value,short:+$('#shortMins').value,long:+$('#longMins').value}))$('#pomoDialog').close();});
$('#dismiss').addEventListener('click',()=>act('dismiss',{id:ringing}));$('#snooze').addEventListener('click',()=>act('dismiss',{id:ringing,snooze:true}));
window.saat.subscribe(next=>{state=next;render()});window.saat.snapshot().then(next=>{state=next;render()});setInterval(render,250);
